### YamlMime:ManagedReference
items:
- uid: BlockEngine.Client.Framework.Configuration.ILoggingSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.ILoggingSettings
  id: ILoggingSettings
  parent: BlockEngine.Client.Framework.Configuration
  children:
  - BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging
  langs:
  - csharp
  - vb
  name: ILoggingSettings
  nameWithType: ILoggingSettings
  fullName: BlockEngine.Client.Framework.Configuration.ILoggingSettings
  type: Interface
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: ILoggingSettings
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 21
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: public interface ILoggingSettings
    content.vb: Public Interface ILoggingSettings
- uid: BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging
  commentId: P:BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging
  id: EnableVerboseLogging
  parent: BlockEngine.Client.Framework.Configuration.ILoggingSettings
  langs:
  - csharp
  - vb
  name: EnableVerboseLogging
  nameWithType: ILoggingSettings.EnableVerboseLogging
  fullName: BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging
  type: Property
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: EnableVerboseLogging
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 23
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: >-
      [Option(Alias = "windowWidth", DefaultValue = "false")]

      bool EnableVerboseLogging { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: >-
      <Option(Alias:="windowWidth", DefaultValue:="false")>

      ReadOnly Property EnableVerboseLogging As Boolean
  overload: BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging*
  attributes:
  - type: Config.Net.OptionAttribute
    ctor: Config.Net.OptionAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Alias
      type: System.String
      value: windowWidth
    - name: DefaultValue
      type: System.String
      value: "false"
references:
- uid: BlockEngine.Client.Framework.Configuration
  commentId: N:BlockEngine.Client.Framework.Configuration
  href: BlockEngine.html
  name: BlockEngine.Client.Framework.Configuration
  nameWithType: BlockEngine.Client.Framework.Configuration
  fullName: BlockEngine.Client.Framework.Configuration
  spec.csharp:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
  spec.vb:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
- uid: BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging*
  commentId: Overload:BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging
  href: BlockEngine.Client.Framework.Configuration.ILoggingSettings.html#BlockEngine_Client_Framework_Configuration_ILoggingSettings_EnableVerboseLogging
  name: EnableVerboseLogging
  nameWithType: ILoggingSettings.EnableVerboseLogging
  fullName: BlockEngine.Client.Framework.Configuration.ILoggingSettings.EnableVerboseLogging
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
