### YamlMime:ManagedReference
items:
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings
  commentId: T:BlockEngine.Client.Framework.Debugging.DebugSettings
  id: DebugSettings
  parent: BlockEngine.Client.Framework.Debugging
  children:
  - BlockEngine.Client.Framework.Debugging.DebugSettings.EnableAmbientOcclusion
  - BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkBorders
  - BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkColumnBorders
  - BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHit
  - BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHitBlock
  - BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastPath
  - BlockEngine.Client.Framework.Debugging.DebugSettings.RenderSkybox
  - BlockEngine.Client.Framework.Debugging.DebugSettings.RenderWireframe
  langs:
  - csharp
  - vb
  name: DebugSettings
  nameWithType: DebugSettings
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings
  type: Class
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: DebugSettings
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 2
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static class DebugSettings
    content.vb: Public Module DebugSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderWireframe
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.RenderWireframe
  id: RenderWireframe
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: RenderWireframe
  nameWithType: DebugSettings.RenderWireframe
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderWireframe
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: RenderWireframe
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 4
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool RenderWireframe
    return:
      type: System.Boolean
    content.vb: Public Shared RenderWireframe As Boolean
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkBorders
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkBorders
  id: RenderChunkBorders
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: RenderChunkBorders
  nameWithType: DebugSettings.RenderChunkBorders
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkBorders
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: RenderChunkBorders
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 5
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool RenderChunkBorders
    return:
      type: System.Boolean
    content.vb: Public Shared RenderChunkBorders As Boolean
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkColumnBorders
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkColumnBorders
  id: RenderChunkColumnBorders
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: RenderChunkColumnBorders
  nameWithType: DebugSettings.RenderChunkColumnBorders
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderChunkColumnBorders
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: RenderChunkColumnBorders
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 6
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool RenderChunkColumnBorders
    return:
      type: System.Boolean
    content.vb: Public Shared RenderChunkColumnBorders As Boolean
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderSkybox
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.RenderSkybox
  id: RenderSkybox
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: RenderSkybox
  nameWithType: DebugSettings.RenderSkybox
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderSkybox
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: RenderSkybox
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 7
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool RenderSkybox
    return:
      type: System.Boolean
    content.vb: Public Shared RenderSkybox As Boolean
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastPath
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastPath
  id: RenderRaycastPath
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: RenderRaycastPath
  nameWithType: DebugSettings.RenderRaycastPath
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastPath
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: RenderRaycastPath
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 8
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool RenderRaycastPath
    return:
      type: System.Boolean
    content.vb: Public Shared RenderRaycastPath As Boolean
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHit
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHit
  id: RenderRaycastHit
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: RenderRaycastHit
  nameWithType: DebugSettings.RenderRaycastHit
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHit
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: RenderRaycastHit
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 9
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool RenderRaycastHit
    return:
      type: System.Boolean
    content.vb: Public Shared RenderRaycastHit As Boolean
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHitBlock
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHitBlock
  id: RenderRaycastHitBlock
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: RenderRaycastHitBlock
  nameWithType: DebugSettings.RenderRaycastHitBlock
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.RenderRaycastHitBlock
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: RenderRaycastHitBlock
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 10
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool RenderRaycastHitBlock
    return:
      type: System.Boolean
    content.vb: Public Shared RenderRaycastHitBlock As Boolean
- uid: BlockEngine.Client.Framework.Debugging.DebugSettings.EnableAmbientOcclusion
  commentId: F:BlockEngine.Client.Framework.Debugging.DebugSettings.EnableAmbientOcclusion
  id: EnableAmbientOcclusion
  parent: BlockEngine.Client.Framework.Debugging.DebugSettings
  langs:
  - csharp
  - vb
  name: EnableAmbientOcclusion
  nameWithType: DebugSettings.EnableAmbientOcclusion
  fullName: BlockEngine.Client.Framework.Debugging.DebugSettings.EnableAmbientOcclusion
  type: Field
  source:
    remote:
      path: source/client/source/Framework/Debugging/DebugSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: EnableAmbientOcclusion
    path: ../source/client/source/Framework/Debugging/DebugSettings.cs
    startLine: 11
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Debugging
  syntax:
    content: public static bool EnableAmbientOcclusion
    return:
      type: System.Boolean
    content.vb: Public Shared EnableAmbientOcclusion As Boolean
references:
- uid: BlockEngine.Client.Framework.Debugging
  commentId: N:BlockEngine.Client.Framework.Debugging
  href: BlockEngine.html
  name: BlockEngine.Client.Framework.Debugging
  nameWithType: BlockEngine.Client.Framework.Debugging
  fullName: BlockEngine.Client.Framework.Debugging
  spec.csharp:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Debugging
    name: Debugging
    href: BlockEngine.Client.Framework.Debugging.html
  spec.vb:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Debugging
    name: Debugging
    href: BlockEngine.Client.Framework.Debugging.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
