### YamlMime:ManagedReference
items:
- uid: BlockEngine.Client.Framework.Configuration.IWindowSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.IWindowSettings
  id: IWindowSettings
  parent: BlockEngine.Client.Framework.Configuration
  children:
  - BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight
  - BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth
  langs:
  - csharp
  - vb
  name: IWindowSettings
  nameWithType: IWindowSettings
  fullName: BlockEngine.Client.Framework.Configuration.IWindowSettings
  type: Interface
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: IWindowSettings
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 11
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: public interface IWindowSettings
    content.vb: Public Interface IWindowSettings
- uid: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth
  commentId: P:BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth
  id: WindowWidth
  parent: BlockEngine.Client.Framework.Configuration.IWindowSettings
  langs:
  - csharp
  - vb
  name: WindowWidth
  nameWithType: IWindowSettings.WindowWidth
  fullName: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth
  type: Property
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: WindowWidth
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 13
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: >-
      [Option(Alias = "windowWidth", DefaultValue = "1280")]

      int WindowWidth { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <Option(Alias:="windowWidth", DefaultValue:="1280")>

      ReadOnly Property WindowWidth As Integer
  overload: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth*
  attributes:
  - type: Config.Net.OptionAttribute
    ctor: Config.Net.OptionAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Alias
      type: System.String
      value: windowWidth
    - name: DefaultValue
      type: System.String
      value: "1280"
- uid: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight
  commentId: P:BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight
  id: WindowHeight
  parent: BlockEngine.Client.Framework.Configuration.IWindowSettings
  langs:
  - csharp
  - vb
  name: WindowHeight
  nameWithType: IWindowSettings.WindowHeight
  fullName: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight
  type: Property
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: WindowHeight
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 15
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: >-
      [Option(Alias = "windowHeight", DefaultValue = "720")]

      int WindowHeight { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <Option(Alias:="windowHeight", DefaultValue:="720")>

      ReadOnly Property WindowHeight As Integer
  overload: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight*
  attributes:
  - type: Config.Net.OptionAttribute
    ctor: Config.Net.OptionAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Alias
      type: System.String
      value: windowHeight
    - name: DefaultValue
      type: System.String
      value: "720"
references:
- uid: BlockEngine.Client.Framework.Configuration
  commentId: N:BlockEngine.Client.Framework.Configuration
  href: BlockEngine.html
  name: BlockEngine.Client.Framework.Configuration
  nameWithType: BlockEngine.Client.Framework.Configuration
  fullName: BlockEngine.Client.Framework.Configuration
  spec.csharp:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
  spec.vb:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
- uid: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth*
  commentId: Overload:BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth
  href: BlockEngine.Client.Framework.Configuration.IWindowSettings.html#BlockEngine_Client_Framework_Configuration_IWindowSettings_WindowWidth
  name: WindowWidth
  nameWithType: IWindowSettings.WindowWidth
  fullName: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowWidth
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight*
  commentId: Overload:BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight
  href: BlockEngine.Client.Framework.Configuration.IWindowSettings.html#BlockEngine_Client_Framework_Configuration_IWindowSettings_WindowHeight
  name: WindowHeight
  nameWithType: IWindowSettings.WindowHeight
  fullName: BlockEngine.Client.Framework.Configuration.IWindowSettings.WindowHeight
