### YamlMime:ManagedReference
items:
- uid: BlockEngine.Client.Framework.Configuration.IClientSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.IClientSettings
  id: IClientSettings
  parent: BlockEngine.Client.Framework.Configuration
  children:
  - BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings
  - BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings
  langs:
  - csharp
  - vb
  name: IClientSettings
  nameWithType: IClientSettings
  fullName: BlockEngine.Client.Framework.Configuration.IClientSettings
  type: Interface
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: IClientSettings
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 4
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: public interface IClientSettings
    content.vb: Public Interface IClientSettings
- uid: BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings
  commentId: P:BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings
  id: WindowSettings
  parent: BlockEngine.Client.Framework.Configuration.IClientSettings
  langs:
  - csharp
  - vb
  name: WindowSettings
  nameWithType: IClientSettings.WindowSettings
  fullName: BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings
  type: Property
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: WindowSettings
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 6
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: IWindowSettings WindowSettings { get; }
    parameters: []
    return:
      type: BlockEngine.Client.Framework.Configuration.IWindowSettings
    content.vb: ReadOnly Property WindowSettings As IWindowSettings
  overload: BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings*
- uid: BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings
  commentId: P:BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings
  id: LoggingSettings
  parent: BlockEngine.Client.Framework.Configuration.IClientSettings
  langs:
  - csharp
  - vb
  name: LoggingSettings
  nameWithType: IClientSettings.LoggingSettings
  fullName: BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings
  type: Property
  source:
    remote:
      path: source/client/source/Framework/Configuration/IClientSettings.cs
      branch: dev
      repo: https://github.com/japsuu/BlockEngine.git
    id: LoggingSettings
    path: ../source/client/source/Framework/Configuration/IClientSettings.cs
    startLine: 7
  assemblies:
  - Client
  namespace: BlockEngine.Client.Framework.Configuration
  syntax:
    content: ILoggingSettings LoggingSettings { get; }
    parameters: []
    return:
      type: BlockEngine.Client.Framework.Configuration.ILoggingSettings
    content.vb: ReadOnly Property LoggingSettings As ILoggingSettings
  overload: BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings*
references:
- uid: BlockEngine.Client.Framework.Configuration
  commentId: N:BlockEngine.Client.Framework.Configuration
  href: BlockEngine.html
  name: BlockEngine.Client.Framework.Configuration
  nameWithType: BlockEngine.Client.Framework.Configuration
  fullName: BlockEngine.Client.Framework.Configuration
  spec.csharp:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
  spec.vb:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
- uid: BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings*
  commentId: Overload:BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings
  href: BlockEngine.Client.Framework.Configuration.IClientSettings.html#BlockEngine_Client_Framework_Configuration_IClientSettings_WindowSettings
  name: WindowSettings
  nameWithType: IClientSettings.WindowSettings
  fullName: BlockEngine.Client.Framework.Configuration.IClientSettings.WindowSettings
- uid: BlockEngine.Client.Framework.Configuration.IWindowSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.IWindowSettings
  parent: BlockEngine.Client.Framework.Configuration
  href: BlockEngine.Client.Framework.Configuration.IWindowSettings.html
  name: IWindowSettings
  nameWithType: IWindowSettings
  fullName: BlockEngine.Client.Framework.Configuration.IWindowSettings
- uid: BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings*
  commentId: Overload:BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings
  href: BlockEngine.Client.Framework.Configuration.IClientSettings.html#BlockEngine_Client_Framework_Configuration_IClientSettings_LoggingSettings
  name: LoggingSettings
  nameWithType: IClientSettings.LoggingSettings
  fullName: BlockEngine.Client.Framework.Configuration.IClientSettings.LoggingSettings
- uid: BlockEngine.Client.Framework.Configuration.ILoggingSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.ILoggingSettings
  parent: BlockEngine.Client.Framework.Configuration
  href: BlockEngine.Client.Framework.Configuration.ILoggingSettings.html
  name: ILoggingSettings
  nameWithType: ILoggingSettings
  fullName: BlockEngine.Client.Framework.Configuration.ILoggingSettings
