### YamlMime:ManagedReference
items:
- uid: BlockEngine.Client.Framework.Configuration
  commentId: N:BlockEngine.Client.Framework.Configuration
  id: BlockEngine.Client.Framework.Configuration
  children:
  - BlockEngine.Client.Framework.Configuration.IClientSettings
  - BlockEngine.Client.Framework.Configuration.ILoggingSettings
  - BlockEngine.Client.Framework.Configuration.IWindowSettings
  - BlockEngine.Client.Framework.Configuration.Settings
  langs:
  - csharp
  - vb
  name: BlockEngine.Client.Framework.Configuration
  nameWithType: BlockEngine.Client.Framework.Configuration
  fullName: BlockEngine.Client.Framework.Configuration
  type: Namespace
  assemblies:
  - Client
references:
- uid: BlockEngine.Client.Framework.Configuration.IClientSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.IClientSettings
  parent: BlockEngine.Client.Framework.Configuration
  href: BlockEngine.Client.Framework.Configuration.IClientSettings.html
  name: IClientSettings
  nameWithType: IClientSettings
  fullName: BlockEngine.Client.Framework.Configuration.IClientSettings
- uid: BlockEngine.Client.Framework.Configuration.IWindowSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.IWindowSettings
  parent: BlockEngine.Client.Framework.Configuration
  href: BlockEngine.Client.Framework.Configuration.IWindowSettings.html
  name: IWindowSettings
  nameWithType: IWindowSettings
  fullName: BlockEngine.Client.Framework.Configuration.IWindowSettings
- uid: BlockEngine.Client.Framework.Configuration.ILoggingSettings
  commentId: T:BlockEngine.Client.Framework.Configuration.ILoggingSettings
  parent: BlockEngine.Client.Framework.Configuration
  href: BlockEngine.Client.Framework.Configuration.ILoggingSettings.html
  name: ILoggingSettings
  nameWithType: ILoggingSettings
  fullName: BlockEngine.Client.Framework.Configuration.ILoggingSettings
- uid: BlockEngine.Client.Framework.Configuration.Settings
  commentId: T:BlockEngine.Client.Framework.Configuration.Settings
  href: BlockEngine.Client.Framework.Configuration.Settings.html
  name: Settings
  nameWithType: Settings
  fullName: BlockEngine.Client.Framework.Configuration.Settings
- uid: BlockEngine.Client.Framework.Configuration
  commentId: N:BlockEngine.Client.Framework.Configuration
  href: BlockEngine.html
  name: BlockEngine.Client.Framework.Configuration
  nameWithType: BlockEngine.Client.Framework.Configuration
  fullName: BlockEngine.Client.Framework.Configuration
  spec.csharp:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
  spec.vb:
  - uid: BlockEngine
    name: BlockEngine
    href: BlockEngine.html
  - name: .
  - uid: BlockEngine.Client
    name: Client
    href: BlockEngine.Client.html
  - name: .
  - uid: BlockEngine.Client.Framework
    name: Framework
    href: BlockEngine.Client.Framework.html
  - name: .
  - uid: BlockEngine.Client.Framework.Configuration
    name: Configuration
    href: BlockEngine.Client.Framework.Configuration.html
